### ISSUE TITLE
False Out of usable balls error

### ISSUE THREAD

**Issue by umutafacan** [earshel/PokeyPySnipe#15]
when it tried to catch, it throws this exception. however when i checked my account i have a lot of balls from each type. It must be derived from another reason.  By the way, i used a couple times after a while i got this error.  When i checked again my pokemon bag is full so this error may happen for that reason. As a humble request you may change exception name.
Line 183,snipe.py - 2016-08-02 19:26:11,077 - INFO - Using a RAZZ_BERRY
[2016-08-02 19:26:14,242] ERROR in app: Exception on /_snipe_ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "snipe.py", line 46, in remote_Snipe
    doSnipe(session,config,snipecoords,pokemonName)
  File "snipe.py", line 283, in doSnipe
    snipe = snipeABitch(session, pokeMon, remoteEncounter)
  File "snipe.py", line 197, in snipeABitch
    raise GeneralPogoException("Out of usable balls")
GeneralPogoException: Out of usable balls
Line 1587,app.py - 2016-08-02 19:26:14,242 - ERROR - Exception on /_snipe_ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "snipe.py", line 46, in remote_Snipe
    doSnipe(session,config,snipecoords,pokemonName)
  File "snipe.py", line 283, in doSnipe
    snipe = snipeABitch(session, pokeMon, remoteEncounter)
  File "snipe.py", line 197, in snipeABitch
    raise GeneralPogoException("Out of usable balls")
GeneralPogoException: Out of usable balls

**Comment by onesvat** [comment]
It is probably caused by out of ultraballs. Another cause of this problem is out of pokemon storage. If you have 250/250 pokemons, it can fail like this.

**Comment by earshel** [comment]
Thank you - I just rewrote the best ball algorithm. Please let me know if you have any further issues with it, as I can't test it in all scenarios (out of each type of ball ,etc)
