### ISSUE TITLE
encrypt.dll error

### ISSUE THREAD

**Issue by akocmark** [earshel/PokeyPySnipe#21]
I tried running the script on mac os x using this command: python snipe.py 
here is my console logs

```
Line 788,connectionpool.py - 2016-08-08 11:07:37,180 - INFO - Starting new HTTPS connection (1): sso.pokemon.com
Line 65,api.py - 2016-08-08 11:07:40,295 - INFO - Coordinates: 25.0805422 55.1403426 8
Line 788,connectionpool.py - 2016-08-08 11:07:40,721 - INFO - Starting new HTTPS connection (1): pgorelease.nianticlabs.com
Traceback (most recent call last):
  File "snipe.py", line 477, in <module>
    session = poko_session.authenticate(locationLookup=config.get('CONFIG','startLoc'))
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/api.py", line 150, in authenticate
    }[self.provider](locationLookup=locationLookup, noop=noop)
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/api.py", line 141, in createPTCSession
    noop=noop
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/api.py", line 73, in createPogoSession
    self.encryptLib
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/session_bare.py", line 51, in __init__
    self.getInventory()
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/session.py", line 40, in getInventory
    self.getProfile()
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/session.py", line 73, in getProfile
    res = self.wrapAndRequest(payload)
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/session_bare.py", line 177, in wrapAndRequest
    res = self.request(self.wrapInRequest(payload, defaults=defaults))
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/session_bare.py", line 124, in wrapInRequest
    signature = hashSignature(proto, self._encryptLib)
  File "/Users/hafizhaseeb/Documents/Pokesnipe/pogo/util.py", line 83, in hashSignature
    library = ctypes.cdll.LoadLibrary(libraryPath)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(encrypt.dll, 6): no suitable image found.  Did find:
    encrypt.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
```

**Comment by akocmark** [comment]
i did try adding the encrypt.so in the same directory, but no luck
Hope you can help me mate, thanks!

**Comment by kriswong** [comment]
Did you try generating your own encryption SO for OSX? Here are the steps.

FRom the terminal -->
wget http://pgoapi.com/pgoencrypt.tar.gz
tar -xzvf pgoencrypt.tar.gz
cd pgoencrypt/src/
make
cd ../../
#make the encrypt able to load
cp pgoencrypt/src/libencrypt.so encrypt.so

**Comment by earshel** [comment]
@akocmark Should not be a problem. I don't have OSX to try this, but go to this repo and download the proper .so file: https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom and put it in the /pogo/ directory. Then change "encrypt.dll" in snipe.py to reflect the name of the file you downloaded.

**Comment by alawing** [comment]
I build a encrypt.so replace it with encrypt.dll worked with MAC thanks!
