### ISSUE TITLE
Line 224,session_bare.py - DATE TIME - ERROR - status_code: 52

### ISSUE THREAD

**Issue by ramonchk** [earshel/PokeyPySnipe#24]
Line 40,demo.py - 2016-08-08 21:06:11,210 - INFO - Finding Nearby Pokemon:
Line 224,session_bare.py - 2016-08-08 21:06:11,496 - ERROR - status_code: 52

Traceback (most recent call last):
  File "demo.py", line 408, in <module>
    pokemon = findBestPokemon(session)
  File "demo.py", line 41, in findBestPokemon
    cells = session.getMapObjects()
  File "C:\pokemon\PokeyPySnipe-master\pogo\session.py", line 100, in getMapObjects
    res = self.wrapAndRequest(payload)
  File "C:\pokemon\PokeyPySnipe-master\pogo\session_bare.py", line 183, in wrapAndRequest
    self.parseDefault(res)
  File "C:\pokemon\PokeyPySnipe-master\pogo\session_bare.py", line 225, in parseDefault
    raise PogoResponseException("Expected response not returned")
custom_exceptions.PogoResponseException: Expected response not returned

**Comment by earshel** [comment]
As far as I'm aware, that just indicates a malformed response from the server. In this case, you should re-start the tool and it will be back to normal.
