### ISSUE TITLE
Snip.py crashs on start up

### ISSUE THREAD

**Issue by Aardwolf2018** [earshel/PokeyPySnipe#29]
If I type `python snipe.py` in my terminal, it will start for a second or so and then crash.
`Line 107,api.py - 2016-08-11 21:55:58,460 - INFO - Creating PTC session for marccin123
Line 788,connectionpool.py - 2016-08-11 21:55:58,481 - INFO - Starting new HTTPS connection (1): sso.pokemon.com
Line 65,api.py - 2016-08-11 21:55:59,959 - INFO - Coordinates: 40.7711329 -73.9741874 8
Line 788,connectionpool.py - 2016-08-11 21:55:59,962 - INFO - Starting new HTTPS connection (1): pgorelease.nianticlabs.com
Traceback (most recent call last):
  File "snipe.py", line 561, in <module>
    session = poko_session.authenticate(locationLookup=config.get('CONFIG','startLoc'))
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/api.py", line 150, in authenticate
    }[self.provider](locationLookup=locationLookup, noop=noop)
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/api.py", line 141, in createPTCSession
    noop=noop
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/api.py", line 73, in createPogoSession
    self.encryptLib
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/session_bare.py", line 51, in __init__
    self.getInventory()
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/session.py", line 40, in getInventory
    self.getProfile()
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/session.py", line 73, in getProfile
    res = self.wrapAndRequest(payload)
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/session_bare.py", line 177, in wrapAndRequest
    res = self.request(self.wrapInRequest(payload, defaults=defaults))
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/session_bare.py", line 124, in wrapInRequest
    signature = hashSignature(proto, self._encryptLib)
  File "/Users/tom/Downloads/PokeyPySnipe-master/pogo/util.py", line 83, in hashSignature
    library = ctypes.cdll.LoadLibrary(libraryPath)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(encrypt/encrypt64bit.dll, 6): no suitable image found.  Did find:
    encrypt/encrypt64bit.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
`
All steps for installation were done before.

**Comment by earshel** [comment]
Sounds like you're on OSX or UNIX of some sort. Please look in to the pogo/encrypt directory, locate the proper file and update your config.ini. This should solve your issue.
